import React, { useState, useEffect, useMemo } from 'react';
import { Link } from 'react-router-dom';
import {
  ArrowRight,
  Clock,
  Calendar,
  BookOpen,
  Search,
  Filter,
  Layers,
  Sparkles,
  ShieldCheck,
  Tag,
  CheckCircle2,
  ExternalLink,
  ChevronRight,
  X,
  FileText
} from 'lucide-react';
import { TopographicBackground } from '../components/TopographicBackground';

export type InsightLabel = 'OBSERVED' | 'MODELLED' | 'SIMULATED' | 'ILLUSTRATIVE' | 'SOURCED';

export interface FieldNote {
  id: string;
  code: string;
  label: InsightLabel;
  category: string;
  title: string;
  subtitle: string;
  readTime: string;
  date: string;
  lastUpdated: string;
  source: string;
  methodology: string;
  sampleSize: string;
  confidence: string;
  // 5-Stage Structure
  observation: string;
  evidence: string;
  interpretation: string;
  systemImplication: string;
  potentialIntervention: string;
  relevantMechanisms: string[];
}

export const FIELD_NOTES: FieldNote[] = [
  {
    id: 'field-note-01',
    code: 'FN-01',
    label: 'OBSERVED',
    category: 'Spatial Economics',
    title: 'Soundstage Dark-Floor Liquidity in Mid-Tier Production Hubs',
    subtitle: 'Analysis of unbooked turnaround intervals between long-term tenant bookings',
    readTime: '6 min read',
    date: 'Q4 2024',
    lastUpdated: 'January 2025',
    source: 'Regional Studio Facility Logs & Production Call-Sheet Audits',
    methodology: 'Direct occupancy log audit across independent soundstage facilities in active filming regions.',
    sampleSize: '18 Stage Complexes across 4 Regional Hubs',
    confidence: 'Observed Empirical Telemetry (High)',
    observation: 'Independent soundstage facilities experience predictable 7-to-21 day "dark intervals" between marquee 6-month studio lease wrap-ups and incoming tenant load-ins. During these windows, facility fixed costs continue while floors generate zero revenue.',
    evidence: 'Over a 12-month monitoring cycle, average annual facility occupancy hovered between 64% and 71%, leaving an aggregate of 92 dark stage days per facility per year.',
    interpretation: 'Traditional multi-month lease agreements enforce all-or-nothing commercial structures that lock out commercial shoots, pickup units, and independent features needing 3-to-5 day floor access.',
    systemImplication: 'Independent productions are forced into non-compliant, acoustically compromised warehouse spaces while pristine commercial soundstage floors sit empty 5 miles away.',
    potentialIntervention: 'Mechanism M10 (Match) & M22 (Capacity Engine): Fractional burst-occupancy covenants that aggregate and schedule micro-turnaround bookings during verified dark dates with zero disruption to incoming long-term tenants.',
    relevantMechanisms: ['M01: Observe', 'M10: Match', 'M22: Capacity Engine']
  },
  {
    id: 'field-note-02',
    code: 'FN-02',
    label: 'MODELLED',
    category: 'Production Variance',
    title: 'The Unapproved Script Revision Blast Radius',
    subtitle: 'Downstream cost velocity generated by mid-production scene alterations',
    readTime: '8 min read',
    date: 'Q1 2025',
    lastUpdated: 'February 2025',
    source: 'DigiSynq Cascade Engine Simulation Model (Version 2.4)',
    methodology: 'Discrete event simulation of 40-day shooting schedule with injected page revisions at Day 14.',
    sampleSize: 'Modelled across 100 Monte Carlo Simulation Runs',
    confidence: 'Modelled Predictive Inference (±8% Variance)',
    observation: 'A seemingly minor 2-page script revision executed during principal photography (introducing a night-for-day exterior and secondary vehicle rig) triggers a non-linear schedule collapse.',
    evidence: 'In simulations, a single un-budgeted night shoot caused a mandatory 12-hour turnaround extension, losing half of the subsequent studio day and pushing the 1st Unit 1.5 days behind schedule.',
    interpretation: 'Production teams routinely treat script changes as localized editorial choices rather than multi-departmental dependency shocks with severe physical constraints.',
    systemImplication: 'Downstream post-production turnover date was delayed by 11 calendar days, forcing the finishing facility into double-time overtime to hit the fixed broadcast window.',
    potentialIntervention: 'Mechanism M07 (Prioritize) & M08 (Simulate): Rapid pre-flight script revision cascade simulation to expose full dollar-velocity and turnaround impact before executive sign-off.',
    relevantMechanisms: ['M07: Prioritize', 'M08: Simulate', 'M18: Escalation']
  },
  {
    id: 'field-note-03',
    code: 'FN-03',
    label: 'SOURCED',
    category: 'Theatrical Yield',
    title: 'Screen Eviction Clustering and Holdover Velocity',
    subtitle: 'Multiplex screen allocation behaviors during saturated territorial release frames',
    readTime: '7 min read',
    date: 'Q3 2024',
    lastUpdated: 'December 2024',
    source: 'National Theatrical Circuit Attendance Registers & Public Box Office Tracking',
    methodology: 'Analysis of weekend-to-weekend screen drop-off percentages across 300+ multiplex screens.',
    sampleSize: '42 Independent Feature Releases (2023–2024)',
    confidence: 'Sourced Historic Industry Data',
    observation: 'Mid-budget and independent titles released during identical calendar windows experience steep screen loss (>45% drop) by their second Friday if opening-weekend per-screen averages fall below threshold markers.',
    evidence: 'When three mid-tier titles opened on the same weekend, aggregate marketing spend was diluted, causing all three to underperform individual per-screen holdover benchmarks.',
    interpretation: 'Exhibitor algorithms ruthlessly reassign screens to high-velocity studio tentpoles when holdover percentages slip, giving nuanced films insufficient runway to build word-of-mouth.',
    systemImplication: 'Producers lose their entire theatrical exploitation window due to uncoordinated release dates, permanently damaging downstream VOD and streaming valuations.',
    potentialIntervention: 'Mechanism M04 (Map) & M11 (Coordinate): Pre-demand territorial release synchronization to staggered secondary windows, prioritizing regional audience density over nationwide saturation.',
    relevantMechanisms: ['M04: Map', 'M11: Coordinate', 'M23: Value Engine']
  },
  {
    id: 'field-note-04',
    code: 'FN-04',
    label: 'OBSERVED',
    category: 'Craft Labor',
    title: 'Informal Phone-Tree Friction in Specialized Guild Crew Assembly',
    subtitle: 'Turnaround latency in securing qualified department heads for short-notice pickup units',
    readTime: '5 min read',
    date: 'Q4 2024',
    lastUpdated: 'January 2025',
    source: 'Independent Producer Guild Logs & Crew Coordinator Post-Mortems',
    methodology: 'Time-to-hire audit for key craft positions (Key Grip, Gaffer, 1st AC, Sound Mixer) across 14 mid-scale productions.',
    sampleSize: '14 Production Units across 3 Regional Markets',
    confidence: 'Observed Field Telemetry (High)',
    observation: 'Producers and line producers spend an average of 42 to 78 hours executing manual phone trees, text chains, and agency calls to assemble verified replacement crew for urgent pickup shoots.',
    evidence: 'In 64% of examined cases, first-choice technicians were unavailable, while certified equivalent technicians sat idle in the same city due to lack of a centralized availability index.',
    interpretation: 'The entertainment industry’s reliance on informal, closed social circles creates artificial labor scarcity and inflated day rates, while underutilizing high-caliber guild craftspeople.',
    systemImplication: 'Productions incur costly schedule pauses or hire unverified personnel, leading to technical mistakes, reshoots, and safety compliance infractions.',
    potentialIntervention: 'Mechanism M09 (Connect) & M10 (Match): Professional Reliability Graph providing verified real-time availability and rate parity matching without agency tolls.',
    relevantMechanisms: ['M09: Connect', 'M10: Match', 'M19: Governance']
  },
  {
    id: 'field-note-05',
    code: 'FN-05',
    label: 'SIMULATED',
    category: 'Post-Production',
    title: 'VFX Turnover Ingestion Bottlenecks and Conformance Rupture',
    subtitle: 'Simulating the impact of incomplete camera metadata on conform timelines',
    readTime: '6 min read',
    date: 'Q1 2025',
    lastUpdated: 'March 2025',
    source: 'DigiSynq System Memory Ingestion Testbed',
    methodology: 'Simulated editorial turnover of 1,200 camera raw takes with variable metadata completeness (85% vs 100%).',
    sampleSize: 'Simulated 50 Editorial Hand-off Scenarios',
    confidence: 'Simulated Synthetic Pipeline Verification',
    observation: 'When production teams deliver camera raw reels with incomplete color space metadata, lens distortion profiles, and missing slate references, editorial conform time triples.',
    evidence: 'In synthetic test runs, an 85% metadata completeness score generated 48 hours of manual conform reconciliation, halting VFX shot dispatch and causing idle vendor artist burn.',
    interpretation: 'Front-end shortcuts taken on set during wrapping are externalized as expensive, high-friction technical crises for post-production finishing teams.',
    systemImplication: 'VFX vendors receive plates 10 days late but are held to the original delivery deadline, resulting in rushed execution, QC failures, and contractual disputes.',
    potentialIntervention: 'Mechanism M01 (Observe) & M13 (Monitor): Camera-to-Cloud telemetry validation at the ingestion gate, rejecting turnovers that fail technical conformance specifications before wrap.',
    relevantMechanisms: ['M01: Observe', 'M13: Monitor', 'M14: Verify']
  },
  {
    id: 'field-note-06',
    code: 'FN-06',
    label: 'ILLUSTRATIVE',
    category: 'Capital Flow',
    title: 'Asset-Light Production vs. Capital Plant Ownership',
    subtitle: 'A comparative balance sheet case study for independent entertainment banners',
    readTime: '9 min read',
    date: 'Q4 2024',
    lastUpdated: 'February 2025',
    source: 'DigiSynq Corporate Architectural Blueprint (Section 36)',
    methodology: 'Financial model comparing 3-year P&L of a studio with owned stages/cameras vs an orchestrated network model.',
    sampleSize: 'Hypothetical Benchmark Production Slate (4 Titles/Year)',
    confidence: 'Illustrative Strategic Framework',
    observation: 'Entertainment companies that invest capital into owning physical real estate and equipment packages face crushing fixed overhead that forces compromise on creative slate selection.',
    evidence: 'In illustrative financial modeling, fixed plant depreciation and debt service consumed 28% of total annual operating budget, creating negative cash flow during production lulls.',
    interpretation: 'In a volatile cyclical industry, enterprise value resides in intellectual property, audience trust, and orchestration intelligence — not in depreciating steel and silicon.',
    systemImplication: 'Studios burdened with heavy asset debt are forced to accept unfavorable distribution deals to meet short-term debt obligations, sacrificing long-term IP equity.',
    potentialIntervention: 'Mechanism M21 (Resilience) & M22 (Capacity Engine): Orchestrate independent partner facilities and verified equipment networks on variable-cost covenants, preserving capital agility.',
    relevantMechanisms: ['M21: Resilience', 'M22: Capacity Engine', 'M23: Value Engine']
  }
];

export function InsightsPage() {
  const [selectedLabel, setSelectedLabel] = useState<string>('ALL');
  const [selectedCategory, setSelectedCategory] = useState<string>('ALL');
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [activeNote, setActiveNote] = useState<FieldNote | null>(null);

  // Categories & Labels
  const categories = useMemo(() => {
    const cats = Array.from(new Set(FIELD_NOTES.map((n) => n.category)));
    return ['ALL', ...cats];
  }, []);

  const labels: (string | InsightLabel)[] = ['ALL', 'OBSERVED', 'MODELLED', 'SOURCED', 'SIMULATED', 'ILLUSTRATIVE'];

  // Filtered Notes
  const filteredNotes = useMemo(() => {
    return FIELD_NOTES.filter((note) => {
      const matchLabel = selectedLabel === 'ALL' || note.label === selectedLabel;
      const matchCat = selectedCategory === 'ALL' || note.category === selectedCategory;
      const q = searchQuery.toLowerCase().trim();
      if (!q) return matchLabel && matchCat;

      const matchSearch =
        note.title.toLowerCase().includes(q) ||
        note.subtitle.toLowerCase().includes(q) ||
        note.observation.toLowerCase().includes(q) ||
        note.systemImplication.toLowerCase().includes(q) ||
        note.potentialIntervention.toLowerCase().includes(q);

      return matchLabel && matchCat && matchSearch;
    });
  }, [selectedLabel, selectedCategory, searchQuery]);

  return (
    <main className="min-h-screen bg-[#03040A] text-[#ECEEF5] pt-28 pb-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto relative">
      <TopographicBackground className="opacity-15 pointer-events-none -z-10 fixed inset-0" />

      {/* Header */}
      <header className="mb-12 max-w-4xl">
        <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full border border-white/10 bg-white/[0.03] text-xs text-zinc-300 font-mono mb-4">
          <span className="w-2 h-2 rounded-full bg-[#52E3A4] animate-pulse" />
          <span>RESEARCH & EVIDENCE DISPATCHES</span>
          <span className="text-zinc-600">//</span>
          <span className="text-[#52E3A4]">DIGISYNQ FIELD NOTES</span>
        </div>

        <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-white mb-4">
          DigiSynq Field Notes.
          <span className="block text-xl sm:text-2xl lg:text-3xl text-zinc-400 font-normal mt-2">
            Empirical Observations, Dependency Telemetry & Systemic Failure Inoculation.
          </span>
        </h1>

        <p className="text-base sm:text-lg text-zinc-400 leading-relaxed font-light">
          We do not publish promotional whitepapers or fabricated surveys. Every dispatch is grounded in observed set logs, verified industry telemetry, or mathematical simulation models.
        </p>

        {/* Filters & Search */}
        <div className="mt-8 space-y-4">
          <div className="relative">
            <Search className="w-4 h-4 text-zinc-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              placeholder="Search field notes by observation, title, or intervention..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-10 pr-4 py-2.5 rounded-xl border border-white/10 bg-[#090B14] text-sm text-white placeholder-zinc-500 focus:outline-none focus:border-[#52E3A4] transition-colors"
            />
          </div>

          <div className="flex flex-wrap items-center justify-between gap-4">
            {/* Label Filter */}
            <div className="flex items-center gap-1.5 overflow-x-auto pb-1 scrollbar-none">
              <span className="text-xs font-mono text-zinc-500 mr-1">DATA TYPE:</span>
              {labels.map((lbl) => (
                <button
                  key={lbl}
                  onClick={() => setSelectedLabel(lbl)}
                  className={`px-2.5 py-1 rounded-lg text-[11px] font-mono whitespace-nowrap transition-colors border ${
                    selectedLabel === lbl
                      ? 'bg-[#16543D] text-[#52E3A4] border-[#52E3A4]'
                      : 'bg-[#090B14] text-zinc-400 border-white/5 hover:border-white/15 hover:text-white'
                  }`}
                >
                  {lbl}
                </button>
              ))}
            </div>

            {/* Category Filter */}
            <div className="flex items-center gap-1.5 overflow-x-auto pb-1 scrollbar-none">
              <span className="text-xs font-mono text-zinc-500 mr-1">TOPIC:</span>
              {categories.map((cat) => (
                <button
                  key={cat}
                  onClick={() => setSelectedCategory(cat)}
                  className={`px-2.5 py-1 rounded-lg text-[11px] font-mono whitespace-nowrap transition-colors border ${
                    selectedCategory === cat
                      ? 'bg-white/15 text-white border-white/30'
                      : 'bg-[#090B14] text-zinc-400 border-white/5 hover:border-white/15 hover:text-white'
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>
        </div>
      </header>

      {/* Field Notes Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-16">
        {filteredNotes.map((note) => {
          const getLabelBadge = (l: InsightLabel) => {
            switch (l) {
              case 'OBSERVED':
                return 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30';
              case 'MODELLED':
                return 'bg-blue-500/10 text-blue-400 border-blue-500/30';
              case 'SIMULATED':
                return 'bg-purple-500/10 text-purple-400 border-purple-500/30';
              case 'SOURCED':
                return 'bg-amber-500/10 text-amber-400 border-amber-500/30';
              case 'ILLUSTRATIVE':
                return 'bg-zinc-500/10 text-zinc-400 border-zinc-500/30';
            }
          };

          return (
            <article
              key={note.id}
              onClick={() => setActiveNote(note)}
              className="p-6 rounded-2xl border border-white/10 bg-[#090B14] hover:border-white/25 transition-all cursor-pointer flex flex-col justify-between group shadow-lg"
            >
              <div>
                <div className="flex items-center justify-between mb-3">
                  <span
                    className={`px-2 py-0.5 rounded text-[10px] font-mono font-bold border ${getLabelBadge(
                      note.label
                    )}`}
                  >
                    {note.label}
                  </span>
                  <span className="text-[10px] font-mono text-zinc-500">{note.code} // {note.readTime}</span>
                </div>

                <div className="text-xs font-mono text-[#52E3A4] mb-1">
                  {note.category}
                </div>

                <h2 className="text-lg font-bold text-white mb-2 group-hover:text-[#52E3A4] transition-colors line-clamp-2">
                  {note.title}
                </h2>

                <p className="text-xs text-zinc-400 leading-relaxed font-light line-clamp-3 mb-4">
                  {note.observation}
                </p>
              </div>

              <div className="pt-4 border-t border-white/5 flex items-center justify-between text-xs font-mono text-zinc-500">
                <span>{note.date}</span>
                <span className="text-[#52E3A4] group-hover:translate-x-1 transition-transform flex items-center gap-1 font-semibold">
                  <span>Read Dossier</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </span>
              </div>
            </article>
          );
        })}
      </div>

      {filteredNotes.length === 0 && (
        <div className="p-12 text-center text-sm text-zinc-500 bg-[#090B14] rounded-2xl border border-white/5 mb-16">
          No dispatches match the selected filters.
        </div>
      )}

      {/* FULL-WIDTH MODAL READER FOR SELECTED FIELD NOTE */}
      {activeNote && (
        <div className="fixed inset-0 z-50 bg-[#03040A]/80 backdrop-blur-md flex items-center justify-center p-4 sm:p-6 overflow-y-auto">
          <div className="bg-[#090B14] border border-white/15 rounded-2xl max-w-4xl w-full max-h-[90vh] overflow-y-auto p-6 sm:p-10 shadow-2xl relative custom-scrollbar">
            {/* Close Button */}
            <button
              onClick={() => setActiveNote(null)}
              className="absolute top-6 right-6 p-2 rounded-xl bg-white/5 hover:bg-white/10 text-zinc-400 hover:text-white transition-colors"
            >
              <X className="w-5 h-5" />
            </button>

            {/* Modal Header */}
            <div className="pb-6 mb-6 border-b border-white/10 pr-10">
              <div className="flex items-center gap-2 mb-2 flex-wrap">
                <span className="px-2.5 py-0.5 rounded text-xs font-mono font-bold bg-[#16543D] text-[#52E3A4] border border-[#52E3A4]/30">
                  {activeNote.label} DISPATCH
                </span>
                <span className="text-xs font-mono text-zinc-500">
                  {activeNote.code} // {activeNote.category}
                </span>
                <span className="text-xs font-mono text-zinc-500">
                  // {activeNote.readTime}
                </span>
              </div>

              <h2 className="text-2xl sm:text-3xl font-bold text-white mb-2">
                {activeNote.title}
              </h2>
              <p className="text-sm text-zinc-400 font-light">
                {activeNote.subtitle}
              </p>

              {/* Rigorous Metadata Bar */}
              <div className="mt-6 p-4 rounded-xl border border-white/5 bg-white/[0.02] grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs font-mono">
                <div>
                  <span className="text-zinc-500 block text-[10px] uppercase">Source</span>
                  <span className="text-zinc-300 font-semibold">{activeNote.source}</span>
                </div>
                <div>
                  <span className="text-zinc-500 block text-[10px] uppercase">Methodology</span>
                  <span className="text-zinc-300 font-semibold">{activeNote.methodology}</span>
                </div>
                <div>
                  <span className="text-zinc-500 block text-[10px] uppercase">Sample / Scope</span>
                  <span className="text-zinc-300 font-semibold">{activeNote.sampleSize}</span>
                </div>
                <div>
                  <span className="text-zinc-500 block text-[10px] uppercase">Confidence</span>
                  <span className="text-[#52E3A4] font-semibold">{activeNote.confidence}</span>
                </div>
              </div>
            </div>

            {/* 5-PART CAUSAL STRUCTURE */}
            <div className="space-y-6 text-sm sm:text-base leading-relaxed mb-8">
              {/* 1. Observation */}
              <div className="p-4 rounded-xl border border-white/10 bg-white/[0.01]">
                <h3 className="text-xs font-mono uppercase tracking-wider text-[#52E3A4] mb-1 font-semibold">
                  01. Observation
                </h3>
                <p className="text-zinc-200 font-light">
                  {activeNote.observation}
                </p>
              </div>

              {/* 2. Evidence */}
              <div className="p-4 rounded-xl border border-white/10 bg-white/[0.01]">
                <h3 className="text-xs font-mono uppercase tracking-wider text-blue-400 mb-1 font-semibold">
                  02. Evidence & Telemetry
                </h3>
                <p className="text-zinc-200 font-light">
                  {activeNote.evidence}
                </p>
              </div>

              {/* 3. Interpretation */}
              <div className="p-4 rounded-xl border border-white/10 bg-white/[0.01]">
                <h3 className="text-xs font-mono uppercase tracking-wider text-amber-400 mb-1 font-semibold">
                  03. Structural Interpretation
                </h3>
                <p className="text-zinc-200 font-light">
                  {activeNote.interpretation}
                </p>
              </div>

              {/* 4. System Implication */}
              <div className="p-4 rounded-xl border border-white/10 bg-white/[0.01]">
                <h3 className="text-xs font-mono uppercase tracking-wider text-purple-400 mb-1 font-semibold">
                  04. System Implication & Blast Radius
                </h3>
                <p className="text-zinc-200 font-light">
                  {activeNote.systemImplication}
                </p>
              </div>

              {/* 5. Potential Intervention */}
              <div className="p-4 rounded-xl border border-[#52E3A4]/30 bg-[#16543D]/20">
                <h3 className="text-xs font-mono uppercase tracking-wider text-[#52E3A4] mb-1 font-semibold">
                  05. DigiSynq Potential Intervention
                </h3>
                <p className="text-zinc-100 font-medium">
                  {activeNote.potentialIntervention}
                </p>
                <div className="mt-3 pt-3 border-t border-[#52E3A4]/20 flex flex-wrap items-center gap-2">
                  <span className="text-[10px] font-mono text-zinc-400 uppercase">Applicable Mechanisms:</span>
                  {activeNote.relevantMechanisms.map((mech) => (
                    <span
                      key={mech}
                      className="px-2 py-0.5 rounded bg-black/40 text-[#52E3A4] text-[10px] font-mono border border-[#52E3A4]/30"
                    >
                      {mech}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            {/* Modal Footer */}
            <div className="pt-6 border-t border-white/10 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div className="text-xs font-mono text-zinc-500">
                Last updated: {activeNote.lastUpdated} // Certified DigiSynq Dispatch
              </div>

              <div className="flex items-center gap-3">
                <button
                  onClick={() => setActiveNote(null)}
                  className="px-4 py-2 rounded-lg bg-white/5 hover:bg-white/10 text-xs font-mono text-zinc-300 transition-colors"
                >
                  Close Dispatch
                </button>
                <Link
                  to={`/start?problem=${encodeURIComponent(activeNote.title)}`}
                  className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg bg-[#52E3A4] text-[#03040A] text-xs font-semibold hover:bg-[#34D399] transition-colors"
                >
                  <span>Resolve Similar Bottleneck</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            </div>
          </div>
        </div>
      )}
    </main>
  );
}
